# Configuración básica
name = "shinyoctopus"
compatibility_date = "2024-05-22"
compatibility_flags = ["streams_enable_constructors"]

# Directorio de salida para Pages
pages_build_output_dir = "dist"

# Configuración de variables de entorno (opcional)
[vars]
# Ejemplo: VARIABLE = "valor"
